---
title: "Projeto Final"
author: "Cristiana Aparecida Nogueira Couto"
date: "06/2020"
output: pdf_document
---

```{r}
library(ggplot2)
library(outbreaks)
library(tidyverse)
library(ggraph)
library(tidygraph)

data("measles_hagelloch_1861")

head(measles_hagelloch_1861)

#Quantidade de pessoas com erupção cutânea reportadas por dia
dates_rash <- table(measles_hagelloch_1861$date_of_rash)

dates_rash <- data.frame(Date = names(dates_rash), 
                        Frequency = as.vector(dates_rash))

dates_rash$Date <- as.Date(dates_rash$Date, format = "%Y-%m-%d")

dates_rash

ggplot(dates_rash) +
  geom_line(aes(x = Date, y = Frequency)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
  plot.title = element_text(hjust = 0.5)) +
  scale_x_date(date_labels = "%d/%m/%Y", date_breaks = "5 day") +
  labs(x = "Datas", y = "Frequência", 
  title = "Pessoas reportadas com erupção cutânea causada por sarampo") 

```

```{r}
#Para quantas pessoas cada indivíduo infectado transmitiu a doença?
infector <- table(measles_hagelloch_1861$infector)
infector <- data.frame(Indivíduo = names(infector), 
                        Infectados_por_ele = as.vector(infector))
infector

#Fazer o espaçamento do eixo y maior
ggplot(infector) +
  geom_point(aes(x = Indivíduo, y = Infectados_por_ele)) +
  coord_flip()

```

```{r}
#Quantas famílias foram afetadas?
ggplot(measles_hagelloch_1861) +
  geom_point(aes(x = case_ID, y = date_of_prodrome, color = factor(family_ID)))
```

```{r}
#Encontrando quem é a família do infector
infecções_fora_da_familia <- cbind(Family_infector= measles_hagelloch_1861$family_ID[measles_hagelloch_1861$infector], 
      Family_person = measles_hagelloch_1861$family_ID)

head(infecções_fora_da_familia)
```

```{r}
#Os indivíduos que estão na mesma familia tem a mesma localização
#Há algo que posso acrescentar na visualização das posições?
ggplot(measles_hagelloch_1861) +
  geom_point(aes(x = x_loc, y = y_loc))
```

```{r}
#ref:
#http://www.hellomister.com.au/data-blog/2019/7/30/creating-an-arc-plot-part-1

infector_edge <- measles_hagelloch_1861 %>%
  select(infector, case_ID) %>%
  rename(from = infector) %>%
  rename(to = case_ID) %>%
  na.omit()

head(infector_edge)

#Quem foi infectado por quem?
infector_tidy <- tbl_graph(edges = infector_edge, directed = TRUE)
infector1 <- ggraph(infector_tidy, layout = 'linear') +
  geom_edge_arc()

infector1

```
